spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/streamsight-db
spring.datasource.username=${DB_USERNAME:streamsight}
spring.datasource.password=${DB_PASSWORD:streamsight}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

app.storage.location=${STORAGE_LOCATION:./uploads}